# WORKFLOW PURPOSE:
# This is a single, intelligent workflow that manages the entire two-phase
# release process. It determines which stage to run based on the context of the
# push event to the 'main' branch, solving race conditions and trigger issues.

name: 'Release Please: Main Workflow'

on:
  push:
    branches:
      - main
  # Allows manual trigger for debugging or re-running a failed process.
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  statuses: write

jobs:
  # ----------------------------------------------------------------------------
  # JOB 1: Prepare Release PR
  # ----------------------------------------------------------------------------
  prepare-release-pr:
    name: '1. Prepare Release PR'
    runs-on: ubuntu-latest
    outputs:
      pr_number: ${{ steps.release-pr.outputs.pr_number }}
    
    # MOTIVATION: This 'if' condition prevents this job from running when the
    # push is a result of merging a Release PR. The string being checked is derived
    # directly from the 'group-pull-request-title-pattern' in the config.
    if: "!contains(github.event.head_commit.message, 'chore(release): prepare new release')"

    steps:
      - name: 'Run Release Please to prepare a Pull Request'
        id: release-pr
        uses: googleapis/release-please-action@v4
        with:
          skip-github-release: true
          config-file: release-please-config.json
          manifest-file: release-please-manifest.json
          token: ${{ secrets.RELEASE_PLEASE_POC_TOKEN }}
          
  # ----------------------------------------------------------------------------
  # JOB 2: Finalize Release
  # ----------------------------------------------------------------------------
  finalize-release:
    name: '2. Finalize Release'
    runs-on: ubuntu-latest
    # MOTIVATION: This 'if' condition ensures this job ONLY runs after a
    # release PR has been merged, acting as the trigger for the finalization stage.
    # The string MUST match the 'group-pull-request-title-pattern' from the config.
    if: "startsWith(github.event.head_commit.message, 'chore(release): prepare new release')"

    steps:
      - name: 'Run Release Please to create GitHub Releases and Tags'
        id: release
        uses: googleapis/release-please-action@v4
        with:
          skip-github-pull-request: true
          config-file: release-please-config.json
          manifest-file: release-please-manifest.json
          token: ${{ secrets.RELEASE_PLEASE_POC_TOKEN }}

  # ----------------------------------------------------------------------------
  # JOB 3: Fix PR Checks
  # ----------------------------------------------------------------------------
  fix-pr-checks:
    name: 'Fix Status Checks on Release PR'
    runs-on: ubuntu-latest
    needs: prepare-release-pr
    if: "always() && needs.prepare-release-pr.result == 'success' && needs.prepare-release-pr.outputs.pr_number"

    steps:
      - name: 'Force re-evaluation of status checks'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.RELEASE_PLEASE_POC_TOKEN }}
          script: |
            const prNumber = ${{ needs.prepare-release-pr.outputs.pr_number }};
            console.log(`Found Release PR #${prNumber}. Triggering check re-run by updating title.`);

            const { data: pr } = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: prNumber,
            });

            await github.rest.pulls.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: prNumber,
              title: pr.title
            });