# REASON: This workflow implements the "finalization" stage of our release process.
# It runs on every push to 'main' to create Git tags and GitHub Releases based on merged Release PRs.
name: '2. Release Please - Finalize'

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please-release:
    name: 'Create Git Tags and GitHub Releases'
    runs-on: ubuntu-latest
    outputs:
      releases_created: ${{ steps.release.outputs.releases_created }}

    steps:
      - name: 'Run Release Please to create releases'
        id: release
        uses: google-github-actions/release-please-action@v4
        with:
          command: github-release
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
          token: ${{ secrets.GITHUB_TOKEN }}

  # A downstream job that runs only if a release was actually created.
  # This can be used to trigger notifications, deployments, etc.
  notify:
    name: 'Notify on Release'
    runs-on: ubuntu-latest
    needs: release-please-release
    if: ${{ needs.release-please-release.outputs.releases_created }}
    steps:
      - name: 'Send notification'
        run: echo "A new release was successfully created."