# REASON: This file defines the GitHub Action that automates release creation.
name: Release Please

on:
  # REASON: This workflow triggers ONLY when a push is made to the 'main' branch.
  push:
    branches:
      - main

jobs:
  release-please:
    # REASON: Defines the name of the job that will appear in the GitHub UI.
    name: Create Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      # REASON: This step runs the main release-please logic.
      - name: Run Release Please for dev
        uses: googleapis/release-please-action@v4
        with:
          # REASON: 'manifest-pr' command tells the action to analyze commits and create/update a Pull Request
          # based on the manifest configuration. It's the "preparation" step.
          command: manifest-pr
          # REASON: Specifies the path to our main config file, which describes the monorepo structure.
          config-file: .release-please-config.json
          # REASON: Specifies the path to the manifest file, which tracks current package versions.
          manifest-file: .release-please-manifest.json

  # === STAGE 2: Create the actual Release when merged into `main` ===
  create-release:
    # REASON: This job ONLY runs for the `main` branch, triggering the final release.
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      # REASON: This step runs the main release-please logic for the finalization.
      - name: Run Release Please for main
        uses: googleapis/release-please-action@v4
        id: release
        with:
          # REASON: 'manifest-release' command reads the manifest, creates Git tags for each released component,
          # and publishes the corresponding GitHub Releases with changelogs.
          command: manifest-release
          # REASON: Specifies the path to our main config file.
          config-file: .release-please-config.json