# REASON: This workflow implements the "preparation" stage of our release process.
# It runs on every push to 'dev' to create or update a Release Pull Request.
name: '1. Release Please - Prepare'

on:
  push:
    branches:
      - dev

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please-pr:
    name: 'Create/Update Release PR'
    runs-on: ubuntu-latest
    steps:
      # REASON: This step checks out the repository code, so that release-please
      # can access the configuration files. It is a mandatory prerequisite.
      - uses: actions/checkout@v4

      - name: 'Run Release Please to prepare a Release PR'
        id: release
        uses: googleapis/release-please-action@v4
        with:
          # REASON: We explicitly tell the action that for this workflow, the target
          # branch is 'dev'. It will look for config files and create the PR against 'dev'.
          target-branch: dev
          # REASON: This flag instructs the action to ONLY create/update a Pull Request.
          # It skips the final release creation step, which is handled by the finalize workflow.
          skip-github-release: true
          # REASON: These inputs point to our manifest-based monorepo configuration.
          config-file: release-please-config.json
          manifest-file: release-please-manifest.json
          token: ${{ secrets.GITHUB_TOKEN }}