# WORKFLOW PURPOSE:
# This workflow ensures all Pull Request titles adhere to the Conventional Commits
# specification. This is critical for our development process.

name: 'Lint PR Title'

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

permissions:
  pull-requests: read
  statuses: write

jobs:
  lint-pr-title:
    name: 'Check PR Title'
    runs-on: ubuntu-latest
    steps:
      - name: 'Check PR title against Conventional Commits'
        uses: amannn/action-semantic-pull-request@v6
        env:
          # This action uses the default GITHUB_TOKEN which is automatically available.
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # A list of valid types, separated by newlines.
          types: |
            feat
            fix
            docs
            style
            refactor
            perf
            test
            build
            ci
            chore
            revert
          # A list of valid scopes, matching our .commitlintrc.json.
          scopes: |
            project
            activity
            payment
            activity-schema
            payment-schema
            release
          # The main description of a commit message should never be empty.
          subjectPattern: ".+"
          subjectPatternError: "The subject of the PR title must not be empty."